# Generated by Django 3.0.6 on 2020-06-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Footballers', '0002_auto_20200619_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballers',
            name='F_goals',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='footballers',
            name='F_id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='footballers',
            name='F_salary',
            field=models.IntegerField(max_length=100),
        ),
    ]
